### ISSUE TITLE
Lower bound greater than upper bound

### ISSUE THREAD

**Issue by mauriceling** [cdanielmachado/embl_gems#1]
Hi,

I've downloaded Pseudomonas_aeruginosa_PAO1.xml.gz and tried to read it into COBRA

>>> from cobra.io.sbml import create_cobra_model_from_sbml_file
>>> model = create_cobra_model_from_sbml_file('Pseudomonas_aeruginosa_PAO1.xml')

However, it give me this error:
Traceback (most recent call last):
  File "D:\Dropbox\Briefcase\BSU_GSM\iBsu1103.py", line 7, in <module>
    model = create_cobra_model_from_sbml_file('Pseudomonas_aeruginosa_PAO1.xml')
  File "C:\Python36\lib\site-packages\cobra\io\sbml.py", line 284, in create_cobra_model_from_sbml_file
    reaction.upper_bound = parameter_dict['upper_bound']
  File "C:\Python36\lib\site-packages\cobra\util\context.py", line 69, in wrapper
    f(self, new_value)
  File "C:\Python36\lib\site-packages\cobra\core\reaction.py", line 232, in upper_bound
    update_forward_and_reverse_bounds(self, 'upper')
  File "C:\Python36\lib\site-packages\cobra\core\reaction.py", line 1115, in update_forward_and_reverse_bounds
    separate_forward_and_reverse_bounds(*reaction.bounds)
  File "C:\Python36\lib\site-packages\cobra\core\reaction.py", line 1093, in separate_forward_and_reverse_bounds
    assert lower_bound <= upper_bound, "lower bound is greater than upper"
AssertionError: lower bound is greater than upper

Is there anything that I can do?

**Comment by cdanielmachado** [comment]
That seems to be a bug within cobrapy, not in the model.

If you open the model using `read_sbml_model` it works:

```model = cobra.io.read_sbml_model('Pseudomonas_aeruginosa_PAO1.xml.gz') ```

Also, you can open it with [framed](https://github.com/cdanielmachado/framed), and it will also load without problems.

**Comment by Midnighter** [comment]
I'm not sure which version of cobrapy you are using but `create_cobra_model_from_sbml_file` is not part of the public interface any longer and is only intended for SBML level 2.  As mentioned above `read_sbml_model` is usually the way to go since it uses libSBML.
